<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="AwesomeAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions.Json" />
    <PackageReference Include="AwesomeAssertions.Web" />
    <PackageReference Include="Ben.Demystifier" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="DeepCloner" />
    <PackageReference Include="Flurl" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Moq.Contrib.HttpClient" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Polly" />
    <PackageReference Include="Roslyn.System.IO.Abstractions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.TestCorrelator" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="WireMock.Net.AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnitTestingCookbook.MinimalApi\UnitTestingCookbook.MinimalApi.csproj" />
    <ProjectReference Include="..\UnitTestingCookbook.Support\UnitTestingCookbook.Support.csproj" />
    <ProjectReference Include="..\UnitTestingCookbook.TestHelpers\UnitTestingCookbook.TestHelpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
